"""Constantes de roles RBAC."""


class Rol:
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN_ESTATAL = "ADMIN_ESTATAL"
    RESPONSABLE_UNIDAD = "RESPONSABLE_UNIDAD"

    TODOS = {SUPER_ADMIN, ADMIN_ESTATAL, RESPONSABLE_UNIDAD}